import type { NutritionItem } from "./types";

export const MOCK_FOODS: NutritionItem[] = [
  {
    id: "oat-bowl",
    name: "Berry Oat Power Bowl",
    emoji: "🥣",
    diet: ["Veg", "Vegan", "Jain"],
    calories: 420,
    protein: 14,
    carbs: 62,
    fats: 12,
    fiber: 9,
    sugar: 14,
    processing: 1,
    ingredients: [
      { name: "Rolled Oats", benefit: "Beta-glucan fiber improves digestion and heart health", area: "digestion" },
      { name: "Blueberries", benefit: "Antioxidants support skin and immunity", area: "skin" },
      { name: "Almonds", benefit: "Vitamin E and healthy fats fuel sustained energy", area: "energy" },
    ],
    insights: ["Excellent fiber balance", "Great morning starter", "Steady energy release"],
  },
  {
    id: "grilled-salmon",
    name: "Grilled Salmon Plate",
    emoji: "🐟",
    diet: ["Non-Veg"],
    calories: 540,
    protein: 38,
    carbs: 32,
    fats: 26,
    fiber: 6,
    sugar: 5,
    processing: 1,
    ingredients: [
      { name: "Salmon", benefit: "Omega-3s support brain function and focus", area: "focus" },
      { name: "Quinoa", benefit: "Complete protein aids muscle recovery", area: "recovery" },
      { name: "Spinach", benefit: "Iron and folate boost immunity", area: "immunity" },
    ],
    insights: ["Excellent protein balance", "Great post-workout meal", "Brain-boosting omega-3s"],
  },
  {
    id: "paneer-wrap",
    name: "Paneer Tikka Wrap",
    emoji: "🌯",
    diet: ["Veg"],
    calories: 480,
    protein: 22,
    carbs: 50,
    fats: 18,
    fiber: 5,
    sugar: 6,
    processing: 2,
    ingredients: [
      { name: "Paneer", benefit: "Calcium and casein support recovery", area: "recovery" },
      { name: "Whole Wheat Wrap", benefit: "Complex carbs fuel steady energy", area: "energy" },
      { name: "Bell Peppers", benefit: "Vitamin C supports immunity", area: "immunity" },
    ],
    insights: ["Balanced macros", "Good post-school refuel", "Moderate processing"],
  },
  {
    id: "chocolate-shake",
    name: "Chocolate Milkshake",
    emoji: "🥤",
    diet: ["Veg"],
    calories: 620,
    protein: 9,
    carbs: 88,
    fats: 22,
    fiber: 1,
    sugar: 64,
    processing: 4,
    ingredients: [
      { name: "Cocoa", benefit: "Flavanols offer mild focus boost", area: "focus" },
      { name: "Milk", benefit: "Protein and calcium for bones", area: "recovery" },
    ],
    insights: ["High sugar spike potential", "Low in fiber", "Treat occasionally"],
  },
  {
    id: "lentil-bowl",
    name: "Lentil & Veggie Bowl",
    emoji: "🥗",
    diet: ["Veg", "Vegan", "Jain"],
    calories: 380,
    protein: 18,
    carbs: 54,
    fats: 8,
    fiber: 14,
    sugar: 7,
    processing: 1,
    ingredients: [
      { name: "Lentils", benefit: "Plant protein and fiber for digestion", area: "digestion" },
      { name: "Carrots", benefit: "Beta-carotene supports skin and eyes", area: "skin" },
      { name: "Turmeric", benefit: "Curcumin supports immunity", area: "immunity" },
    ],
    insights: ["Excellent fiber balance", "Plant-powered protein", "Anti-inflammatory"],
  },
  {
    id: "chicken-rice",
    name: "Chicken & Brown Rice",
    emoji: "🍚",
    diet: ["Non-Veg"],
    calories: 560,
    protein: 42,
    carbs: 60,
    fats: 14,
    fiber: 7,
    sugar: 4,
    processing: 1,
    ingredients: [
      { name: "Chicken Breast", benefit: "Lean protein for muscle recovery", area: "recovery" },
      { name: "Brown Rice", benefit: "Complex carbs sustain energy", area: "energy" },
      { name: "Broccoli", benefit: "Vitamin C and K boost immunity", area: "immunity" },
    ],
    insights: ["Excellent protein balance", "Great post-workout meal", "Whole-food quality"],
  },
];
